In [15]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [16]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [17]:
df.shape

(569, 33)

In [18]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [19]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train test split

In [20]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [21]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [22]:
X_train

array([[-0.27629532,  2.01775935, -0.30630783, ..., -0.53847052,
        -0.67152175, -1.09393997],
       [-0.8975103 , -0.1171556 , -0.79793395, ...,  2.17867493,
         2.04077489,  3.24814192],
       [ 1.67192818,  0.21360587,  1.63047834, ...,  0.74636414,
        -0.5488956 ,  0.44727877],
       ...,
       [-0.58252806, -0.30219698, -0.5860847 , ..., -0.89505459,
        -0.77962637, -0.35795508],
       [-1.88591291,  1.41174882, -1.85760477, ..., -1.00353916,
        -0.16004165,  1.31947236],
       [-0.08963918, -0.9614069 , -0.13181877, ..., -0.21851965,
         0.10618615, -0.82552868]], shape=(455, 30))

In [23]:
X_test

array([[ 0.38623244,  0.47235024,  0.42400133, ...,  1.30584555,
         0.092029  ,  0.95840507],
       [-0.26064323,  0.40068678, -0.29506479, ..., -0.74714895,
         0.40875387, -1.05518746],
       [-0.05105551,  1.11015509,  0.00346446, ...,  1.14072169,
         2.43710586,  1.14756827],
       ...,
       [-0.41848089, -0.38761134, -0.40149696, ..., -0.26842623,
        -0.20992631,  1.3068636 ],
       [-0.8143688 ,  0.56790153, -0.85133049, ..., -1.60633889,
        -0.80234951, -0.97703319],
       [ 1.27633335,  0.52729223,  1.19164798, ...,  0.83503785,
        -0.64973079, -0.97852659]], shape=(114, 30))

In [24]:
y_train

543    B
379    M
517    M
190    M
378    B
      ..
11     M
498    M
480    B
539    B
279    B
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [25]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [26]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0])

In [27]:
y_test

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1])

# Numpy arrays to PyTorch tensors

In [28]:
X_train_tensor = torch.from_numpy(X_train)
x_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [29]:
X_train_tensor.shape

torch.Size([455, 30])

In [30]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [31]:
class MyNN():

    def __init__(self,X):

        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

    def forward(self, X):
        z =torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self,y_pred,y):

        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

Important parameters

In [32]:
learning_rate = 0.1
epochs = 25

Training Pipeline

In [33]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self,num_features):

        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):

        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [34]:
# create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forward pass
#model.forward(feature)
model(features)

tensor([[0.4363],
        [0.4553],
        [0.4363],
        [0.4363],
        [0.4363],
        [0.4363],
        [0.4363],
        [0.4363],
        [0.4363],
        [0.4363]], grad_fn=<SigmoidBackward0>)

In [35]:
#show model weights
model.linear2.weight

Parameter containing:
tensor([[-0.1142,  0.3064,  0.0958]], requires_grad=True)

In [36]:
from torchinfo import summary

summary(model,input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

In [37]:
# Create a model
model = MyNN(X_train_tensor)

#define loop
for epoch in range(epochs):
# forward bias
  y_pred = model.forward(X_train_tensor)
  print(y_pred)
# loss calculate
  loss = model.loss_function(y_pred,y_train_tensor)
#backward bias 
  loss.backward()
#parameter update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
# zero gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()
# print loss in each epoch
  print('Epoch:' ,{epoch + 1}, 'Loss:' ,{loss.item()})

tensor([[1.2601e-02],
        [9.9995e-01],
        [9.9031e-01],
        [1.0000e+00],
        [6.1902e-03],
        [7.2327e-02],
        [2.2031e-04],
        [7.1229e-01],
        [2.7920e-04],
        [4.1079e-05],
        [6.9145e-01],
        [9.9998e-01],
        [1.0000e+00],
        [2.6983e-02],
        [1.3998e-01],
        [6.4787e-02],
        [2.1415e-03],
        [9.9499e-01],
        [9.9868e-01],
        [1.2091e-02],
        [1.9860e-01],
        [3.1058e-02],
        [9.9492e-01],
        [9.9079e-01],
        [1.5605e-02],
        [9.1168e-01],
        [7.3326e-01],
        [9.9992e-01],
        [9.9999e-01],
        [9.9998e-01],
        [9.9862e-01],
        [1.6234e-04],
        [2.3144e-02],
        [2.0608e-03],
        [3.0320e-03],
        [4.9734e-03],
        [4.1205e-04],
        [2.0194e-04],
        [7.9514e-06],
        [9.9224e-01],
        [9.9774e-01],
        [7.9303e-06],
        [2.1127e-04],
        [9.9982e-01],
        [1.5686e-03],
        [4.1436e-01],
        [4.6292e-01],
        [9.1555e-04],
        [3.5474e-02],
        [9.9940e-01],
        [1.2228e-03],
        [5.0990e-01],
        [1.1363e-02],
        [8.2271e-01],
        [6.1182e-01],
        [5.5984e-04],
        [9.8156e-01],
        [9.9709e-01],
        [7.8797e-01],
        [1.3485e-04],
        [1.5965e-01],
        [9.9613e-01],
        [3.6337e-03],
        [4.0173e-03],
        [2.7839e-01],
        [9.3507e-01],
        [8.0764e-04],
        [3.9450e-03],
        [1.1183e-02],
        [1.8675e-05],
        [9.9562e-01],
        [9.9491e-01],
        [2.2336e-02],
        [4.8131e-02],
        [9.9931e-01],
        [1.6531e-01],
        [1.0305e-03],
        [1.4454e-01],
        [1.7819e-04],
        [9.9944e-01],
        [4.7848e-02],
        [9.9990e-01],
        [1.0000e+00],
        [2.5403e-03],
        [7.0472e-01],
        [1.2621e-03],
        [1.6951e-01],
        [9.0863e-01],
        [2.6250e-03],
        [4.9141e-04],
        [9.9998e-01],
        [3.0768e-02],
        [1.0000e+00],
        [4.0475e-05],
        [8.9932e-02],
        [9.9994e-01],
        [9.9348e-01],
        [1.0000e+00],
        [1.2674e-02],
        [8.7173e-02],
        [2.0109e-02],
        [2.9133e-02],
        [8.9581e-02],
        [3.9134e-02],
        [1.0000e+00],
        [5.1966e-06],
        [9.9990e-01],
        [9.9997e-01],
        [3.4616e-02],
        [3.4192e-02],
        [1.0000e+00],
        [1.0000e+00],
        [3.8901e-04],
        [5.2736e-06],
        [1.3838e-04],
        [9.9999e-01],
        [5.6437e-01],
        [1.3978e-02],
        [3.6533e-06],
        [2.7511e-02],
        [1.0000e+00],
        [7.1508e-03],
        [8.7258e-01],
        [9.9927e-01],
        [9.9970e-01],
        [6.3528e-04],
        [9.8309e-01],
        [9.9989e-01],
        [2.8571e-02],
        [1.9759e-02],
        [9.9988e-01],
        [9.9998e-01],
        [6.7629e-01],
        [9.9986e-01],
        [9.6773e-05],
        [3.5255e-02],
        [9.9993e-01],
        [1.0642e-02],
        [5.1331e-05],
        [9.9957e-01],
        [9.6987e-01],
        [1.5562e-02],
        [4.1824e-04],
        [8.1340e-01],
        [2.5926e-02],
        [1.2487e-01],
        [5.5613e-01],
        [4.3176e-02],
        [1.2102e-01],
        [1.0000e+00],
        [9.3846e-01],
        [1.9915e-02],
        [1.0000e+00],
        [9.3860e-03],
        [9.6312e-01],
        [9.7579e-01],
        [9.1601e-01],
        [7.6330e-04],
        [5.3960e-05],
        [7.0822e-02],
        [2.1287e-03],
        [1.2178e-02],
        [9.0451e-02],
        [9.9983e-01],
        [1.1856e-03],
        [9.9788e-01],
        [3.9837e-05],
        [1.0446e-01],
        [1.7797e-01],
        [1.0000e+00],
        [9.9949e-01],
        [9.9784e-01],
        [1.2558e-04],
        [9.9993e-01],
        [7.2483e-03],
        [8.9814e-01],
        [1.9405e-02],
        [1.4227e-01],
        [6.7805e-03],
        [9.9999e-01],
        [1.0000e+00],
        [9.8288e-01],
        [9.3458e-01],
        [9.9997e-01],
        [9.9999e-01],
        [7.7463e-01],
        [1.0645e-02],
        [3.6185e-03],
        [1.3087e-06],
        [2.6826e-04],
        [6.3649e-05],
        [6.2025e-01],
        [1.0561e-03],
        [4.6199e-06],
        [1.0000e+00],
        [1.0513e-01],
        [1.3544e-03],
        [1.7173e-03],
        [6.9381e-01],
        [9.9993e-01],
        [1.9104e-03],
        [1.8453e-04],
        [3.2694e-02],
        [1.0425e-01],
        [5.4694e-02],
        [9.9911e-01],
        [3.0597e-02],
        [7.7900e-01],
        [2.4705e-02],
        [1.2091e-02],
        [4.0650e-04],
        [7.3311e-02],
        [8.5054e-04],
        [9.8719e-01],
        [4.3563e-04],
        [2.2182e-04],
        [2.9255e-01],
        [2.1412e-02],
        [3.7430e-01],
        [2.3338e-05],
        [8.1365e-02],
        [6.8410e-03],
        [5.8967e-04],
        [7.9336e-03],
        [1.5066e-02],
        [6.6858e-04],
        [9.9777e-01],
        [1.0000e+00],
        [9.5357e-01],
        [4.4274e-03],
        [1.2093e-04],
        [5.5183e-01],
        [1.0000e+00],
        [2.4127e-03],
        [1.3417e-03],
        [6.4198e-03],
        [2.5489e-01],
        [3.1326e-02],
        [9.6113e-01],
        [9.9991e-01],
        [6.4581e-02],
        [3.7306e-04],
        [7.5793e-01],
        [9.9051e-01],
        [7.4793e-01],
        [1.3540e-02],
        [9.9807e-01],
        [3.0352e-02],
        [1.9537e-03],
        [1.0345e-03],
        [9.8537e-01],
        [7.6623e-03],
        [5.2289e-04],
        [9.7045e-01],
        [4.2010e-05],
        [1.4447e-02],
        [5.1993e-06],
        [8.8996e-01],
        [9.9998e-01],
        [3.0985e-03],
        [9.9999e-01],
        [1.0000e+00],
        [7.0400e-05],
        [9.9650e-01],
        [4.0251e-01],
        [3.2635e-02],
        [9.9985e-01],
        [9.9994e-01],
        [5.2477e-01],
        [9.9945e-01],
        [4.1854e-04],
        [4.3468e-01],
        [1.5887e-02],
        [9.9551e-01],
        [9.9965e-01],
        [2.7630e-05],
        [1.7012e-03],
        [1.5679e-03],
        [1.3087e-01],
        [9.9878e-01],
        [1.0000e+00],
        [5.0802e-03],
        [5.5938e-02],
        [1.0000e+00],
        [1.2574e-02],
        [9.9996e-01],
        [5.3588e-04],
        [1.2817e-01],
        [2.9702e-01],
        [1.7194e-03],
        [9.9999e-01],
        [1.0304e-05],
        [9.6833e-01],
        [9.5342e-01],
        [4.0857e-04],
        [8.9399e-04],
        [2.2996e-02],
        [3.0459e-04],
        [9.9827e-01],
        [1.0725e-02],
        [9.9999e-01],
        [1.2326e-03],
        [4.3815e-02],
        [2.8806e-02],
        [1.4821e-04],
        [1.0000e+00],
        [9.2932e-04],
        [9.9794e-01],
        [9.8154e-01],
        [1.0000e+00],
        [1.0874e-03],
        [6.6081e-04],
        [4.7717e-06],
        [9.9967e-01],
        [7.6851e-04],
        [6.8833e-01],
        [2.6212e-04],
        [1.0293e-04],
        [2.6010e-04],
        [2.8667e-02],
        [2.7743e-03],
        [7.9841e-05],
        [1.7376e-04],
        [1.1015e-01],
        [1.1350e-01],
        [9.9928e-01],
        [1.5091e-03],
        [4.1328e-05],
        [1.3905e-05],
        [9.2410e-03],
        [8.2347e-01],
        [6.3458e-06],
        [9.9998e-01],
        [9.9992e-01],
        [1.0000e+00],
        [1.0000e+00],
        [8.8454e-01],
        [9.9954e-01],
        [2.8428e-03],
        [9.9999e-01],
        [3.5207e-02],
        [6.0404e-05],
        [9.9952e-01],
        [9.9665e-01],
        [5.1383e-01],
        [4.3452e-01],
        [3.3165e-04],
        [8.3500e-05],
        [9.9953e-01],
        [4.2010e-01],
        [9.7827e-01],
        [8.4214e-01],
        [3.4112e-03],
        [1.7569e-03],
        [4.5412e-02],
        [2.4275e-02],
        [1.0000e+00],
        [3.2375e-01],
        [9.9967e-01],
        [9.5638e-01],
        [9.9987e-01],
        [2.2116e-04],
        [1.0000e+00],
        [7.5430e-01],
        [9.6793e-01],
        [2.7731e-05],
        [4.0355e-04],
        [9.8904e-01],
        [6.1067e-02],
        [8.4618e-04],
        [8.3776e-01],
        [3.3743e-04],
        [9.9056e-01],
        [1.0000e+00],
        [8.0128e-03],
        [1.5016e-01],
        [9.6285e-01],
        [2.9570e-02],
        [4.7822e-01],
        [1.4493e-04],
        [2.6545e-02],
        [1.2213e-03],
        [9.9949e-01],
        [3.7091e-04],
        [1.3545e-03],
        [9.9989e-01],
        [2.5853e-01],
        [3.0732e-03],
        [1.7047e-03],
        [1.3929e-03],
        [1.6864e-03],
        [1.1971e-04],
        [8.1512e-01],
        [7.9394e-01],
        [9.9950e-01],
        [9.9995e-01],
        [1.0000e+00],
        [3.5704e-01],
        [1.5580e-03],
        [4.3673e-01],
        [9.9992e-01],
        [9.9992e-01],
        [8.6907e-04],
        [3.5981e-01],
        [4.7217e-01],
        [7.3715e-04],
        [1.0000e+00],
        [9.9997e-01],
        [4.8247e-03],
        [9.9999e-01],
        [9.8515e-01],
        [6.8663e-03],
        [9.9807e-01],
        [9.9835e-03],
        [3.4263e-02],
        [9.9903e-01],
        [8.4091e-01],
        [4.6146e-02],
        [9.9997e-01],
        [2.6865e-01],
        [1.0000e+00],
        [8.6455e-02],
        [1.0000e+00],
        [9.9996e-01],
        [9.9754e-01],
        [6.0796e-05],
        [1.0000e+00],
        [1.3970e-01],
        [8.0990e-01],
        [2.9060e-02],
        [7.8004e-02],
        [1.0981e-04],
        [7.9679e-01],
        [9.9356e-01],
        [9.9753e-01],
        [3.0781e-04],
        [9.1727e-05],
        [5.1678e-02],
        [2.0724e-04],
        [7.2664e-03],
        [1.3795e-04],
        [1.3797e-02],
        [8.6805e-01],
        [8.4746e-04],
        [5.8720e-01],
        [8.0627e-03],
        [1.0000e+00],
        [9.9999e-01],
        [9.9995e-01],
        [3.1770e-02],
        [9.9344e-01],
        [9.9920e-01],
        [5.6845e-04],
        [9.5902e-01],
        [5.3013e-03]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)
Epoch: {1} Loss: {3.1718039755244796}
tensor([[1.6971e-02],
        [9.9991e-01],
        [9.8542e-01],
        [1.0000e+00],
        [7.6793e-03],
        [9.0373e-02],
        [3.7936e-04],
        [6.7361e-01],
        [4.2476e-04],
        [6.9918e-05],
        [7.0067e-01],
        [9.9996e-01],
        [9.9999e-01],
        [3.0272e-02],
        [1.6586e-01],
        [7.5843e-02],
        [2.8612e-03],
        [9.9369e-01],
        [9.9776e-01],
        [1.5411e-02],
        [1.8461e-01],
        [3.2621e-02],
        [9.9258e-01],
        [9.8813e-01],
        [1.8485e-02],
        [8.9460e-01],
        [7.4960e-01],
        [9.9988e-01],
        [9.9997e-01],
        [9.9996e-01],
        [9.9785e-01],
        [2.6980e-04],
        [2.5963e-02],
        [4.1304e-03],
        [4.6051e-03],
        [6.7803e-03],
        [5.6986e-04],
        [3.0801e-04],
        [1.5299e-05],
        [9.9096e-01],
        [9.9676e-01],
        [1.4663e-05],
        [3.0619e-04],
        [9.9969e-01],
        [2.8384e-03],
        [4.2746e-01],
        [5.0306e-01],
        [1.2578e-03],
        [5.0698e-02],
        [9.9909e-01],
        [1.6040e-03],
        [5.2552e-01],
        [1.4049e-02],
        [7.8773e-01],
        [5.6649e-01],
        [8.0657e-04],
        [9.7427e-01],
        [9.9589e-01],
        [8.0745e-01],
        [1.9913e-04],
        [1.6792e-01],
        [9.9417e-01],
        [4.7793e-03],
        [5.6481e-03],
        [2.9127e-01],
        [9.2026e-01],
        [1.2919e-03],
        [4.7213e-03],
        [1.4826e-02],
        [3.2360e-05],
        [9.9387e-01],
        [9.9277e-01],
        [3.2482e-02],
        [5.1120e-02],
        [9.9872e-01],
        [1.9520e-01],
        [1.3995e-03],
        [1.5171e-01],
        [2.6368e-04],
        [9.9912e-01],
        [6.0227e-02],
        [9.9980e-01],
        [9.9999e-01],
        [3.3185e-03],
        [6.6274e-01],
        [1.8285e-03],
        [1.9365e-01],
        [8.9532e-01],
        [3.5844e-03],
        [6.9254e-04],
        [9.9997e-01],
        [4.8490e-02],
        [1.0000e+00],
        [8.0354e-05],
        [1.0558e-01],
        [9.9988e-01],
        [9.9023e-01],
        [1.0000e+00],
        [1.6268e-02],
        [9.3881e-02],
        [2.7848e-02],
        [3.0030e-02],
        [1.1749e-01],
        [5.7850e-02],
        [9.9999e-01],
        [1.0187e-05],
        [9.9988e-01],
        [9.9994e-01],
        [5.0522e-02],
        [4.3621e-02],
        [1.0000e+00],
        [1.0000e+00],
        [5.9674e-04],
        [9.7612e-06],
        [2.1180e-04],
        [9.9997e-01],
        [5.2845e-01],
        [1.5657e-02],
        [6.5993e-06],
        [3.4543e-02],
        [1.0000e+00],
        [9.7030e-03],
        [8.7393e-01],
        [9.9860e-01],
        [9.9966e-01],
        [9.5852e-04],
        [9.8157e-01],
        [9.9978e-01],
        [3.2123e-02],
        [2.2534e-02],
        [9.9979e-01],
        [9.9997e-01],
        [6.7792e-01],
        [9.9977e-01],
        [1.5536e-04],
        [4.7939e-02],
        [9.9991e-01],
        [1.3823e-02],
        [8.2796e-05],
        [9.9926e-01],
        [9.5499e-01],
        [1.9121e-02],
        [6.8041e-04],
        [7.7994e-01],
        [3.3626e-02],
        [1.3835e-01],
        [5.7733e-01],
        [4.8364e-02],
        [1.2757e-01],
        [9.9999e-01],
        [9.3200e-01],
        [2.5810e-02],
        [1.0000e+00],
        [1.1733e-02],
        [9.5383e-01],
        [9.7482e-01],
        [9.0119e-01],
        [1.1723e-03],
        [9.1146e-05],
        [8.2832e-02],
        [3.1496e-03],
        [1.7443e-02],
        [1.0230e-01],
        [9.9969e-01],
        [1.4691e-03],
        [9.9663e-01],
        [6.4722e-05],
        [1.0835e-01],
        [1.8452e-01],
        [1.0000e+00],
        [9.9928e-01],
        [9.9671e-01],
        [1.8554e-04],
        [9.9988e-01],
        [8.6301e-03],
        [9.0693e-01],
        [2.3026e-02],
        [1.5279e-01],
        [8.6616e-03],
        [9.9998e-01],
        [1.0000e+00],
        [9.7555e-01],
        [9.2232e-01],
        [9.9994e-01],
        [9.9998e-01],
        [8.1693e-01],
        [1.4316e-02],
        [5.4632e-03],
        [2.4989e-06],
        [3.9494e-04],
        [1.0849e-04],
        [6.4452e-01],
        [1.8097e-03],
        [8.1988e-06],
        [1.0000e+00],
        [1.3311e-01],
        [1.8310e-03],
        [2.8756e-03],
        [7.4485e-01],
        [9.9990e-01],
        [2.7345e-03],
        [2.7934e-04],
        [3.9573e-02],
        [1.4556e-01],
        [5.6856e-02],
        [9.9853e-01],
        [4.1232e-02],
        [7.5078e-01],
        [3.1751e-02],
        [1.5176e-02],
        [6.0784e-04],
        [8.1422e-02],
        [1.2399e-03],
        [9.8007e-01],
        [7.8947e-04],
        [3.9186e-04],
        [3.5247e-01],
        [2.6309e-02],
        [3.3977e-01],
        [4.2988e-05],
        [1.0621e-01],
        [9.1694e-03],
        [8.4927e-04],
        [1.2135e-02],
        [2.1195e-02],
        [9.7826e-04],
        [9.9693e-01],
        [1.0000e+00],
        [9.4615e-01],
        [5.3206e-03],
        [1.7561e-04],
        [5.6029e-01],
        [1.0000e+00],
        [3.0779e-03],
        [1.7743e-03],
        [8.1953e-03],
        [2.8433e-01],
        [4.9092e-02],
        [9.5814e-01],
        [9.9983e-01],
        [8.1033e-02],
        [5.7107e-04],
        [7.5095e-01],
        [9.8728e-01],
        [7.9102e-01],
        [2.1647e-02],
        [9.9713e-01],
        [3.3593e-02],
        [2.7145e-03],
        [1.5179e-03],
        [9.8375e-01],
        [1.0917e-02],
        [7.9460e-04],
        [9.6238e-01],
        [7.4696e-05],
        [1.6983e-02],
        [9.8759e-06],
        [8.8078e-01],
        [9.9997e-01],
        [3.8918e-03],
        [9.9998e-01],
        [1.0000e+00],
        [1.0750e-04],
        [9.9517e-01],
        [4.2472e-01],
        [3.2815e-02],
        [9.9973e-01],
        [9.9990e-01],
        [5.5317e-01],
        [9.9914e-01],
        [6.5601e-04],
        [4.2616e-01],
        [2.0043e-02],
        [9.9494e-01],
        [9.9946e-01],
        [4.4161e-05],
        [2.2478e-03],
        [2.1787e-03],
        [1.4249e-01],
        [9.9818e-01],
        [1.0000e+00],
        [6.5824e-03],
        [6.4072e-02],
        [1.0000e+00],
        [1.7288e-02],
        [9.9993e-01],
        [6.9760e-04],
        [1.4371e-01],
        [2.8973e-01],
        [2.4774e-03],
        [9.9998e-01],
        [1.9080e-05],
        [9.6600e-01],
        [9.4002e-01],
        [6.0073e-04],
        [1.2145e-03],
        [3.0529e-02],
        [4.9360e-04],
        [9.9805e-01],
        [1.3241e-02],
        [9.9997e-01],
        [1.8222e-03],
        [4.9593e-02],
        [3.3694e-02],
        [2.3207e-04],
        [1.0000e+00],
        [1.2247e-03],
        [9.9714e-01],
        [9.7441e-01],
        [1.0000e+00],
        [1.5213e-03],
        [9.1720e-04],
        [8.9431e-06],
        [9.9949e-01],
        [1.1999e-03],
        [6.4019e-01],
        [4.2362e-04],
        [1.7667e-04],
        [3.7369e-04],
        [3.1320e-02],
        [4.3764e-03],
        [1.2853e-04],
        [2.4124e-04],
        [1.2036e-01],
        [1.1852e-01],
        [9.9903e-01],
        [2.4622e-03],
        [7.3584e-05],
        [2.6189e-05],
        [1.3862e-02],
        [7.9161e-01],
        [1.1688e-05],
        [9.9997e-01],
        [9.9987e-01],
        [1.0000e+00],
        [9.9999e-01],
        [8.6801e-01],
        [9.9930e-01],
        [4.4730e-03],
        [9.9997e-01],
        [4.2631e-02],
        [1.0960e-04],
        [9.9923e-01],
        [9.9481e-01],
        [5.3390e-01],
        [4.3342e-01],
        [4.5690e-04],
        [1.3105e-04],
        [9.9930e-01],
        [4.1272e-01],
        [9.7360e-01],
        [8.4667e-01],
        [4.5275e-03],
        [2.8005e-03],
        [5.6979e-02],
        [3.0606e-02],
        [1.0000e+00],
        [3.5271e-01],
        [9.9953e-01],
        [9.5304e-01],
        [9.9976e-01],
        [3.6203e-04],
        [9.9999e-01],
        [7.8548e-01],
        [9.5625e-01],
        [4.8722e-05],
        [6.3571e-04],
        [9.8527e-01],
        [7.4750e-02],
        [1.3003e-03],
        [7.9898e-01],
        [4.9505e-04],
        [9.8580e-01],
        [1.0000e+00],
        [1.2096e-02],
        [1.5427e-01],
        [9.4950e-01],
        [3.1689e-02],
        [4.5430e-01],
        [2.4485e-04],
        [3.1371e-02],
        [1.8862e-03],
        [9.9924e-01],
        [5.2108e-04],
        [2.0907e-03],
        [9.9982e-01],
        [2.5249e-01],
        [4.4233e-03],
        [2.4030e-03],
        [1.9644e-03],
        [2.4361e-03],
        [1.8342e-04],
        [7.8523e-01],
        [8.2862e-01],
        [9.9919e-01],
        [9.9992e-01],
        [1.0000e+00],
        [3.8068e-01],
        [2.0944e-03],
        [4.8643e-01],
        [9.9990e-01],
        [9.9986e-01],
        [1.2842e-03],
        [3.7241e-01],
        [4.5601e-01],
        [1.1985e-03],
        [1.0000e+00],
        [9.9996e-01],
        [6.3299e-03],
        [9.9998e-01],
        [9.8081e-01],
        [8.7368e-03],
        [9.9704e-01],
        [1.5753e-02],
        [3.6529e-02],
        [9.9869e-01],
        [8.1729e-01],
        [5.1709e-02],
        [9.9996e-01],
        [3.1493e-01],
        [1.0000e+00],
        [1.0587e-01],
        [1.0000e+00],
        [9.9993e-01],
        [9.9593e-01],
        [1.2107e-04],
        [1.0000e+00],
        [1.5452e-01],
        [7.8720e-01],
        [3.8895e-02],
        [9.1338e-02],
        [1.4928e-04],
        [8.1485e-01],
        [9.9058e-01],
        [9.9620e-01],
        [4.5286e-04],
        [1.4301e-04],
        [7.5576e-02],
        [3.1271e-04],
        [9.5911e-03],
        [2.1172e-04],
        [1.8282e-02],
        [8.6116e-01],
        [1.2657e-03],
        [6.0010e-01],
        [9.6008e-03],
        [1.0000e+00],
        [9.9999e-01],
        [9.9992e-01],
        [3.6399e-02],

In [38]:
model.bias

tensor([-0.1609], dtype=torch.float64, requires_grad=True)