In [159]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [160]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [161]:
df.shape

(569, 33)

In [162]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [163]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train test split

In [164]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [165]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [166]:
X_train

array([[-0.28071485,  0.35280814, -0.24677155, ...,  0.06686294,
        -0.54930597, -0.11635998],
       [-0.17230824, -0.0740536 , -0.15675308, ...,  0.4927928 ,
        -0.37864133, -0.38414086],
       [ 2.18626803,  0.73352268,  2.13192401, ...,  1.68758871,
        -1.38274588, -0.69746643],
       ...,
       [-0.59714495, -0.07174624, -0.64251312, ..., -0.9849646 ,
        -0.02405656, -0.16629453],
       [-1.06007048,  0.14976039, -1.06458084, ..., -0.72768417,
        -0.01908574, -0.35011951],
       [-0.83153763,  0.172834  , -0.76735005, ..., -0.32399035,
         0.10021381, -0.75563195]], shape=(455, 30))

In [167]:
X_test

array([[-0.09535923,  0.26526127, -0.10777559, ..., -0.68047229,
        -1.00585674,  0.0366118 ],
       [-0.01117332,  0.22412529, -0.00989948, ...,  0.22375978,
        -0.58219674, -0.32963795],
       [ 0.14444306, -1.18659683,  0.07351765, ..., -0.52711895,
        -0.879502  , -1.32093854],
       ...,
       [-0.52139094, -1.06318889, -0.54376915, ..., -0.85855558,
        -0.39340789, -0.27013681],
       [-0.66680296,  2.34383811, -0.6601824 , ..., -0.68185385,
        -0.06191252, -0.69819843],
       [-0.81221498, -1.15513991, -0.82924113, ..., -0.85855558,
        -0.49895126,  0.42134734]], shape=(114, 30))

In [168]:
y_train

466    B
396    B
564    M
256    M
158    B
      ..
255    M
341    B
346    B
245    B
288    B
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [169]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [170]:
y_train

array([0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0])

In [171]:
y_test

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0])

# Numpy arrays to PyTorch tensors

In [172]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
x_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [173]:
X_train_tensor.shape

torch.Size([455, 30])

In [174]:
y_train_tensor.shape

torch.Size([455])

In [175]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return len(self.features)

  def __getitem__(self, idx):

    return self.features[idx], self.labels[idx]

In [176]:
train_dataset = CustomDatasets(X_train_tensor,y_train_tensor)
test_dataset = CustomDatasets(x_test_tensor,y_test_tensor)

In [177]:
train_dataset[10]

(tensor([-1.0513,  0.2259, -0.9831, -0.9276,  1.1593,  0.4972, -0.3111, -0.4796,
          0.3961,  2.1585, -0.2501,  1.1961, -0.4017, -0.4332,  1.6911,  0.6565,
          0.4173,  0.5592,  0.3009,  1.0609, -1.0779, -0.4585, -1.0522, -0.9002,
         -0.0822, -0.3045, -0.6803, -0.8216, -0.8476,  0.3512]),
 tensor(0.))

In [178]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

# Defining the model

Important parameters

In [179]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [180]:
learning_rate = 0.1
epochs = 25

Training Pipeline

In [181]:
#create model
model = MySimpleNN(X_train_tensor.shape[1])

#define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)

#define loss function
loss_function = nn.BCELoss()

In [182]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[-0.1485,  0.1064,  0.0402,  0.0564, -0.1151,  0.0767, -0.1068, -0.1693,
          0.1025,  0.1522, -0.0432,  0.0122, -0.0961,  0.0564, -0.1661,  0.1532,
         -0.0227, -0.0067, -0.1345,  0.0562,  0.0154,  0.1346,  0.0637,  0.1584,
          0.0875,  0.0532, -0.1209,  0.0621, -0.1445, -0.1606]],
       requires_grad=True)

In [183]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)

In [184]:

# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.2361210584640503
Epoch: 2, Loss: 0.18694761395454407
Epoch: 3, Loss: 0.2286083996295929
Epoch: 4, Loss: 0.08718795329332352
Epoch: 5, Loss: 0.09980117529630661
Epoch: 6, Loss: 0.024989310652017593
Epoch: 7, Loss: 0.030626151710748672
Epoch: 8, Loss: 0.0449402742087841
Epoch: 9, Loss: 0.27476364374160767
Epoch: 10, Loss: 0.02697119489312172
Epoch: 11, Loss: 0.07949577271938324
Epoch: 12, Loss: 0.11071942746639252
Epoch: 13, Loss: 0.031261395663022995
Epoch: 14, Loss: 0.06385953724384308
Epoch: 15, Loss: 0.006009414792060852
Epoch: 16, Loss: 0.08528714627027512
Epoch: 17, Loss: 0.13193944096565247
Epoch: 18, Loss: 0.7391533255577087
Epoch: 19, Loss: 0.02663305588066578
Epoch: 20, Loss: 0.15092523396015167
Epoch: 21, Loss: 0.07340426743030548
Epoch: 22, Loss: 0.15629146993160248
Epoch: 23, Loss: 0.0722905769944191
Epoch: 24, Loss: 0.16219164431095123
Epoch: 25, Loss: 0.012447730638086796

In [185]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9332