In [95]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [96]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [97]:
df.shape

(569, 33)

In [98]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [99]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

# Train test split

In [100]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [101]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(x_test)

In [102]:
X_train

array([[-1.0979381 , -1.00091766, -1.10408228, ..., -1.34783608,
         1.08667105, -0.22603762],
       [-0.73006691, -1.06891632, -0.72294996, ..., -0.61754123,
         0.05898524,  0.44408154],
       [ 1.38240556,  1.32745038,  1.46977215, ...,  2.01630658,
         2.94351247,  1.13730826],
       ...,
       [-1.30249678, -0.19431282, -1.29505219, ..., -0.97561449,
        -0.75348716, -0.1590257 ],
       [-0.45695041, -0.43113575, -0.46213271, ..., -0.15109776,
         0.21580742, -0.43342794],
       [ 0.53240015,  0.95931969,  0.43619296, ..., -0.23463313,
         0.07066348,  0.023524  ]], shape=(455, 30))

In [103]:
X_test

array([[-0.11688117,  0.11258652, -0.09057082, ...,  0.45100249,
        -0.2239871 ,  0.29094112],
       [-0.54708508, -0.15693104, -0.56229617, ..., -0.37776791,
         0.6109006 , -0.49426331],
       [-0.68356356, -0.26862301, -0.66467961, ..., -0.17678199,
        -0.69251058, -0.32965143],
       ...,
       [-0.25039273,  1.59857525, -0.31733745, ..., -0.82433299,
        -0.75239703, -0.88543163],
       [-0.81707512, -0.11565358, -0.74760174, ...,  0.1521328 ,
         0.76942358,  2.66031986],
       [-0.72510049, -0.64254827, -0.68287171, ..., -0.02655648,
        -0.14824834, -0.51892642]], shape=(114, 30))

In [104]:
y_train

60     B
478    B
42     M
231    B
85     M
      ..
563    M
343    M
359    B
497    B
10     M
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [105]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [106]:
y_train

array([0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1])

In [107]:
y_test

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0])

# Numpy arrays to PyTorch tensors

In [108]:
X_train_tensor = torch.from_numpy(X_train)
x_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [109]:
X_train_tensor.shape

torch.Size([455, 30])

In [110]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [111]:
class MyNN():

    def __init__(self,X):

        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

    def forward(self, X):
        z =torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self,y_pred,y):

        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

Important parameters

In [112]:
learning_rate = 0.1
epochs = 25

Training Pipeline

In [118]:
# Create a model
model = MyNN(X_train_tensor)

#define loop
for epoch in range(epochs):
# forward bias
  y_pred = model.forward(X_train_tensor)
  print(y_pred)
# loss calculate
  loss = model.loss_function(y_pred,y_train_tensor)
#backward bias 
  loss.backward()
#parameter update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
# zero gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()
# print loss in each epoch
  print('Epoch:' ,{epoch + 1}, 'Loss:' ,{loss.item()})

tensor([[4.9080e-03],
        [2.7204e-03],
        [1.0000e+00],
        [2.3253e-05],
        [9.9916e-01],
        [1.0000e+00],
        [9.6284e-03],
        [9.9957e-01],
        [6.3670e-05],
        [1.3702e-02],
        [6.0333e-01],
        [1.9791e-05],
        [3.1652e-04],
        [3.4189e-03],
        [1.9811e-04],
        [2.0176e-05],
        [3.7852e-04],
        [9.9987e-01],
        [2.6069e-04],
        [9.5718e-01],
        [8.5910e-01],
        [8.3025e-04],
        [2.6062e-01],
        [7.4151e-05],
        [2.7748e-06],
        [2.9046e-01],
        [5.3222e-04],
        [1.0281e-04],
        [9.9832e-01],
        [2.4682e-03],
        [1.8554e-06],
        [9.9893e-01],
        [2.7876e-05],
        [7.0957e-02],
        [1.0000e+00],
        [9.9999e-01],
        [1.6514e-02],
        [7.5798e-01],
        [8.6490e-07],
        [9.1258e-01],
        [9.9996e-01],
        [9.9519e-01],
        [5.4366e-07],
        [1.0000e+00],
        [9.9994e-01],
        [4.0026e-02],
        [2.6082e-02],
        [2.4762e-02],
        [1.0000e+00],
        [1.0000e+00],
        [2.0514e-04],
        [7.0648e-01],
        [9.8979e-01],
        [1.4020e-01],
        [9.4725e-01],
        [9.6579e-02],
        [9.5407e-01],
        [1.8904e-03],
        [3.5335e-01],
        [9.9955e-01],
        [8.4235e-04],
        [9.9877e-01],
        [1.0000e+00],
        [1.2724e-03],
        [8.0433e-01],
        [5.1361e-03],
        [2.0655e-05],
        [9.9987e-01],
        [1.5522e-05],
        [3.0849e-02],
        [7.0015e-06],
        [9.9801e-01],
        [1.1929e-03],
        [7.6491e-01],
        [9.8524e-01],
        [6.5015e-01],
        [9.9288e-01],
        [9.9999e-01],
        [9.9787e-01],
        [1.3824e-05],
        [1.9317e-04],
        [9.9999e-01],
        [2.5173e-07],
        [1.1899e-03],
        [7.8250e-03],
        [3.1122e-02],
        [4.8056e-06],
        [9.9998e-01],
        [9.9785e-01],
        [8.0710e-01],
        [9.9954e-01],
        [7.9468e-03],
        [2.3711e-03],
        [2.2728e-01],
        [9.9982e-01],
        [1.0056e-04],
        [9.9132e-01],
        [7.4417e-01],
        [9.9998e-01],
        [3.0131e-03],
        [1.1876e-04],
        [6.3401e-02],
        [7.1902e-03],
        [9.2492e-01],
        [4.6467e-04],
        [9.9986e-01],
        [1.2576e-03],
        [8.6487e-01],
        [9.9983e-01],
        [4.3407e-02],
        [9.8900e-01],
        [6.8811e-05],
        [9.8852e-01],
        [9.9999e-01],
        [9.9990e-01],
        [7.2744e-05],
        [4.0627e-01],
        [7.2380e-01],
        [2.5341e-02],
        [9.9072e-02],
        [3.5919e-07],
        [9.9968e-01],
        [1.7623e-03],
        [2.3726e-03],
        [9.9999e-01],
        [6.8020e-02],
        [7.7869e-01],
        [9.1307e-04],
        [9.5520e-01],
        [1.0000e+00],
        [6.2234e-01],
        [3.8975e-01],
        [1.3853e-02],
        [3.7335e-03],
        [1.1205e-03],
        [1.0000e+00],
        [5.8287e-05],
        [4.9540e-04],
        [9.9268e-05],
        [2.3032e-03],
        [1.7984e-03],
        [5.3889e-02],
        [2.2571e-04],
        [1.2462e-02],
        [3.9799e-02],
        [7.6610e-02],
        [3.1366e-04],
        [1.0000e+00],
        [6.8277e-01],
        [1.9945e-04],
        [1.1843e-02],
        [6.9993e-07],
        [8.8132e-04],
        [1.6431e-01],
        [9.5820e-01],
        [1.4762e-03],
        [7.4458e-02],
        [2.2398e-02],
        [1.0000e+00],
        [1.0000e+00],
        [9.8829e-01],
        [1.0000e+00],
        [6.7320e-04],
        [9.9946e-01],
        [9.7259e-05],
        [1.0815e-04],
        [1.2457e-05],
        [9.9179e-01],
        [2.0398e-02],
        [2.3540e-05],
        [9.9971e-01],
        [7.4070e-03],
        [1.4805e-04],
        [3.2427e-03],
        [9.7040e-01],
        [1.0000e+00],
        [2.4923e-05],
        [8.6618e-04],
        [9.9760e-01],
        [9.9996e-01],
        [2.8533e-05],
        [1.2699e-01],
        [3.5369e-03],
        [9.9885e-01],
        [4.4212e-04],
        [1.0000e+00],
        [8.6816e-04],
        [4.0490e-03],
        [8.2220e-01],
        [8.5600e-04],
        [4.6010e-04],
        [9.9546e-01],
        [6.4213e-02],
        [7.4001e-01],
        [5.8753e-02],
        [2.3141e-03],
        [4.1826e-04],
        [3.3210e-03],
        [2.6296e-03],
        [7.7493e-04],
        [9.9984e-01],
        [2.1172e-03],
        [4.5519e-07],
        [4.0270e-02],
        [1.0000e+00],
        [1.0000e+00],
        [4.8125e-01],
        [4.9122e-05],
        [9.3237e-03],
        [9.9775e-01],
        [9.9340e-01],
        [9.9716e-03],
        [4.4706e-02],
        [2.8181e-01],
        [9.9996e-01],
        [5.8445e-02],
        [1.1546e-03],
        [1.0000e+00],
        [2.4615e-04],
        [1.0054e-05],
        [1.2260e-01],
        [4.1792e-01],
        [1.3734e-04],
        [8.7839e-07],
        [2.7565e-01],
        [1.0000e+00],
        [3.7586e-03],
        [1.0000e+00],
        [9.6156e-01],
        [6.1461e-02],
        [8.2641e-04],
        [1.0000e+00],
        [9.5484e-04],
        [9.1554e-04],
        [9.9998e-01],
        [9.3026e-03],
        [1.0000e+00],
        [1.0000e+00],
        [4.2987e-02],
        [9.9998e-01],
        [5.0436e-02],
        [3.9069e-03],
        [5.8118e-06],
        [9.9783e-01],
        [1.0000e+00],
        [9.8758e-01],
        [2.2172e-01],
        [2.2243e-04],
        [8.4379e-01],
        [7.1729e-01],
        [2.6290e-03],
        [6.2237e-03],
        [1.6953e-03],
        [9.6884e-01],
        [9.9996e-01],
        [6.5362e-03],
        [9.8626e-01],
        [9.9994e-01],
        [9.9999e-01],
        [9.6677e-01],
        [4.2913e-02],
        [9.9740e-01],
        [5.6920e-02],
        [1.5894e-02],
        [1.0000e+00],
        [9.9998e-01],
        [9.6377e-02],
        [5.8723e-03],
        [3.5204e-01],
        [3.9980e-05],
        [4.7238e-04],
        [9.9832e-01],
        [9.9994e-01],
        [2.1935e-04],
        [4.2097e-03],
        [2.6597e-02],
        [1.1501e-05],
        [6.7768e-05],
        [9.9975e-01],
        [1.4097e-01],
        [6.8680e-04],
        [1.0000e+00],
        [1.0000e+00],
        [2.8581e-01],
        [9.9973e-01],
        [1.0571e-02],
        [1.4879e-01],
        [1.0000e+00],
        [1.1221e-01],
        [3.0177e-05],
        [6.6328e-01],
        [9.9928e-01],
        [2.1646e-05],
        [9.9996e-01],
        [9.2736e-06],
        [9.9999e-01],
        [1.0000e+00],
        [4.5429e-03],
        [9.9988e-01],
        [5.5176e-04],
        [3.2288e-02],
        [4.8395e-01],
        [3.6634e-01],
        [2.6945e-04],
        [9.1807e-01],
        [1.1380e-02],
        [2.2869e-01],
        [4.7778e-03],
        [2.3578e-03],
        [2.0055e-03],
        [9.4784e-06],
        [8.0318e-04],
        [8.7236e-01],
        [6.1809e-07],
        [9.3035e-01],
        [9.9999e-01],
        [9.9771e-01],
        [9.8948e-01],
        [1.0934e-04],
        [1.5395e-04],
        [1.9743e-03],
        [1.4740e-02],
        [8.2929e-03],
        [1.5521e-03],
        [1.0000e+00],
        [1.0000e+00],
        [1.0000e+00],
        [2.3104e-05],
        [1.4120e-02],
        [8.6546e-03],
        [5.5088e-01],
        [6.7434e-02],
        [1.0000e+00],
        [9.9962e-01],
        [1.0000e+00],
        [2.8569e-03],
        [1.0000e+00],
        [9.9914e-01],
        [1.0000e+00],
        [1.6769e-02],
        [3.2501e-05],
        [8.6049e-04],
        [1.1408e-02],
        [1.0000e+00],
        [3.5005e-05],
        [4.1866e-07],
        [3.0598e-01],
        [9.9989e-01],
        [7.1496e-04],
        [9.8968e-01],
        [1.5154e-04],
        [3.8659e-05],
        [2.8827e-01],
        [9.9999e-01],
        [9.8154e-01],
        [9.5365e-01],
        [1.0000e+00],
        [5.2229e-02],
        [1.6838e-02],
        [3.4211e-04],
        [8.4688e-01],
        [4.3455e-02],
        [6.4410e-01],
        [1.3979e-04],
        [9.9995e-01],
        [1.3120e-04],
        [9.1126e-01],
        [1.8354e-03],
        [2.1926e-01],
        [6.7536e-04],
        [3.6974e-04],
        [2.3624e-06],
        [5.4636e-06],
        [7.5325e-07],
        [1.0000e+00],
        [1.0000e+00],
        [3.5887e-04],
        [2.7676e-04],
        [9.6211e-01],
        [1.8321e-05],
        [9.9998e-01],
        [3.4983e-06],
        [9.7232e-01],
        [1.0000e+00],
        [1.2030e-01],
        [3.8129e-05],
        [9.9999e-01],
        [1.0005e-04],
        [9.9998e-01],
        [4.0263e-01],
        [9.9855e-01],
        [1.0000e+00],
        [4.6779e-01],
        [5.3743e-05],
        [9.9993e-01],
        [1.7469e-02],
        [9.1643e-01],
        [9.1731e-01],
        [8.6398e-01],
        [9.9996e-01],
        [1.0522e-05],
        [9.9777e-01],
        [3.7830e-01],
        [2.5498e-01],
        [1.0000e+00],
        [3.9648e-04],
        [1.7492e-06],
        [7.7237e-01],
        [1.5423e-05],
        [1.0000e+00],
        [9.7347e-05],
        [9.9999e-01],
        [5.5889e-04],
        [1.0000e+00],
        [3.6589e-04],
        [7.7415e-01],
        [1.0000e+00],
        [3.8169e-01],
        [1.4237e-03],
        [1.1338e-04],
        [9.9849e-01],
        [2.3740e-03],
        [5.2630e-05],
        [7.2460e-05],
        [7.9805e-06],
        [4.7198e-02],
        [3.0573e-02],
        [1.1027e-07],
        [4.7552e-01],
        [9.9985e-01],
        [1.1366e-02],
        [8.9101e-01],
        [2.6019e-06],
        [1.0000e+00],
        [3.0098e-02],
        [8.3831e-03],
        [9.9980e-01],
        [1.0000e+00],
        [9.9443e-01],
        [1.4584e-02],
        [9.9943e-01],
        [2.3421e-01],
        [8.1524e-04],
        [9.9999e-01],
        [9.9969e-01],
        [1.2176e-02],
        [1.0017e-04],
        [2.7877e-06],
        [1.0000e+00],
        [2.0938e-03],
        [1.0000e+00],
        [9.9999e-01],
        [2.8808e-03],
        [3.4836e-04],
        [5.3204e-02]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)
Epoch: {1} Loss: {3.6665948341636962}
tensor([[6.4441e-03],
        [3.4121e-03],
        [1.0000e+00],
        [3.6062e-05],
        [9.9885e-01],
        [1.0000e+00],
        [1.1473e-02],
        [9.9935e-01],
        [9.1472e-05],
        [1.6951e-02],
        [5.9215e-01],
        [2.9210e-05],
        [4.3774e-04],
        [4.0218e-03],
        [2.6915e-04],
        [3.2858e-05],
        [5.2171e-04],
        [9.9983e-01],
        [3.9388e-04],
        [9.4752e-01],
        [8.3800e-01],
        [1.0758e-03],
        [2.8193e-01],
        [9.6094e-05],
        [4.3090e-06],
        [3.0094e-01],
        [7.7624e-04],
        [1.4285e-04],
        [9.9769e-01],
        [2.9986e-03],
        [3.0283e-06],
        [9.9861e-01],
        [4.3499e-05],
        [8.8925e-02],
        [1.0000e+00],
        [9.9999e-01],
        [2.1719e-02],
        [7.6501e-01],
        [1.4749e-06],
        [9.0143e-01],
        [9.9995e-01],
        [9.9336e-01],
        [9.4746e-07],
        [1.0000e+00],
        [9.9991e-01],
        [4.6484e-02],
        [3.3238e-02],
        [3.0056e-02],
        [1.0000e+00],
        [1.0000e+00],
        [2.7055e-04],
        [7.0071e-01],
        [9.8551e-01],
        [1.4982e-01],
        [9.3987e-01],
        [1.0749e-01],
        [9.5281e-01],
        [2.4165e-03],
        [3.6729e-01],
        [9.9935e-01],
        [1.1909e-03],
        [9.9845e-01],
        [1.0000e+00],
        [1.6905e-03],
        [7.8657e-01],
        [5.9629e-03],
        [3.1265e-05],
        [9.9981e-01],
        [2.3092e-05],
        [3.1278e-02],
        [1.1273e-05],
        [9.9713e-01],
        [1.5590e-03],
        [7.8495e-01],
        [9.8016e-01],
        [6.3212e-01],
        [9.9111e-01],
        [9.9998e-01],
        [9.9762e-01],
        [1.9679e-05],
        [2.9123e-04],
        [9.9998e-01],
        [4.3181e-07],
        [1.7094e-03],
        [1.0617e-02],
        [3.7637e-02],
        [7.8827e-06],
        [9.9997e-01],
        [9.9757e-01],
        [8.0589e-01],
        [9.9939e-01],
        [1.0047e-02],
        [3.4412e-03],
        [2.3446e-01],
        [9.9972e-01],
        [1.7158e-04],
        [9.8824e-01],
        [7.5645e-01],
        [9.9996e-01],
        [3.9886e-03],
        [1.7918e-04],
        [6.6353e-02],
        [9.5808e-03],
        [9.1316e-01],
        [7.0322e-04],
        [9.9982e-01],
        [1.5845e-03],
        [8.4091e-01],
        [9.9975e-01],
        [4.3381e-02],
        [9.8658e-01],
        [9.7993e-05],
        [9.8547e-01],
        [9.9999e-01],
        [9.9984e-01],
        [1.0280e-04],
        [4.5066e-01],
        [7.2811e-01],
        [2.9950e-02],
        [1.2200e-01],
        [6.2920e-07],
        [9.9960e-01],
        [2.7395e-03],
        [3.0786e-03],
        [9.9998e-01],
        [7.9298e-02],
        [7.9549e-01],
        [1.1877e-03],
        [9.5271e-01],
        [1.0000e+00],
        [6.4768e-01],
        [4.1637e-01],
        [1.7116e-02],
        [5.3116e-03],
        [1.6331e-03],
        [1.0000e+00],
        [8.3768e-05],
        [6.6142e-04],
        [1.5185e-04],
        [2.6995e-03],
        [2.2700e-03],
        [6.2747e-02],
        [3.0322e-04],
        [1.5395e-02],
        [4.7354e-02],
        [8.2301e-02],
        [4.1316e-04],
        [1.0000e+00],
        [6.7905e-01],
        [2.5922e-04],
        [1.4605e-02],
        [1.2729e-06],
        [1.1476e-03],
        [2.0104e-01],
        [9.5109e-01],
        [1.9929e-03],
        [8.6590e-02],
        [2.5686e-02],
        [1.0000e+00],
        [1.0000e+00],
        [9.8350e-01],
        [1.0000e+00],
        [8.5148e-04],
        [9.9922e-01],
        [1.4085e-04],
        [1.4705e-04],
        [2.0594e-05],
        [9.8959e-01],
        [2.3257e-02],
        [3.8347e-05],
        [9.9958e-01],
        [9.5729e-03],
        [2.1629e-04],
        [4.3453e-03],
        [9.6586e-01],
        [1.0000e+00],
        [3.7175e-05],
        [1.2160e-03],
        [9.9656e-01],
        [9.9994e-01],
        [4.0801e-05],
        [1.3261e-01],
        [4.4087e-03],
        [9.9838e-01],
        [5.7092e-04],
        [1.0000e+00],
        [1.1888e-03],
        [4.7966e-03],
        [8.0928e-01],
        [1.0719e-03],
        [6.2146e-04],
        [9.9394e-01],
        [7.0848e-02],
        [7.5427e-01],
        [6.4972e-02],
        [3.1773e-03],
        [5.7902e-04],
        [4.2900e-03],
        [3.0939e-03],
        [1.0431e-03],
        [9.9978e-01],
        [2.8621e-03],
        [8.1354e-07],
        [4.1352e-02],
        [1.0000e+00],
        [1.0000e+00],
        [4.9801e-01],
        [7.0719e-05],
        [1.0817e-02],
        [9.9718e-01],
        [9.9143e-01],
        [1.2867e-02],
        [5.6892e-02],
        [2.8055e-01],
        [9.9993e-01],
        [6.1470e-02],
        [1.5119e-03],
        [9.9999e-01],
        [3.7670e-04],
        [1.6038e-05],
        [1.3330e-01],
        [4.4455e-01],
        [1.9899e-04],
        [1.5830e-06],
        [2.7066e-01],
        [1.0000e+00],
        [4.7778e-03],
        [1.0000e+00],
        [9.5281e-01],
        [6.5864e-02],
        [1.1248e-03],
        [1.0000e+00],
        [1.3764e-03],
        [1.2435e-03],
        [9.9996e-01],
        [1.0423e-02],
        [1.0000e+00],
        [1.0000e+00],
        [4.9574e-02],
        [9.9997e-01],
        [5.9595e-02],
        [4.3896e-03],
        [9.5444e-06],
        [9.9707e-01],
        [1.0000e+00],
        [9.8602e-01],
        [2.2417e-01],
        [3.2959e-04],
        [8.2592e-01],
        [7.0276e-01],
        [3.2092e-03],
        [7.6460e-03],
        [2.2917e-03],
        [9.6997e-01],
        [9.9993e-01],
        [7.8490e-03],
        [9.8295e-01],
        [9.9990e-01],
        [9.9999e-01],
        [9.6250e-01],
        [4.8499e-02],
        [9.9636e-01],
        [6.2624e-02],
        [1.8663e-02],
        [1.0000e+00],
        [9.9996e-01],
        [1.0972e-01],
        [7.3595e-03],
        [3.5489e-01],
        [5.7743e-05],
        [6.7230e-04],
        [9.9778e-01],
        [9.9991e-01],
        [3.1664e-04],
        [6.1213e-03],
        [3.2051e-02],
        [1.7381e-05],
        [1.0001e-04],
        [9.9963e-01],
        [1.4131e-01],
        [8.8155e-04],
        [1.0000e+00],
        [1.0000e+00],
        [3.3066e-01],
        [9.9965e-01],
        [1.5577e-02],
        [1.7414e-01],
        [1.0000e+00],
        [1.1996e-01],
        [4.1314e-05],
        [6.6528e-01],
        [9.9894e-01],
        [3.1160e-05],
        [9.9994e-01],
        [1.5002e-05],
        [9.9998e-01],
        [1.0000e+00],
        [5.8397e-03],
        [9.9982e-01],
        [7.9525e-04],
        [3.9944e-02],
        [4.9643e-01],
        [3.7825e-01],
        [3.8880e-04],
        [9.0308e-01],
        [1.2633e-02],
        [2.6547e-01],
        [5.4481e-03],
        [3.0520e-03],
        [2.7193e-03],
        [1.5371e-05],
        [1.1184e-03],
        [8.5622e-01],
        [1.0832e-06],
        [9.1902e-01],
        [9.9998e-01],
        [9.9707e-01],
        [9.8897e-01],
        [1.4357e-04],
        [2.0169e-04],
        [2.4257e-03],
        [1.7039e-02],
        [9.2573e-03],
        [2.0155e-03],
        [1.0000e+00],
        [1.0000e+00],
        [1.0000e+00],
        [3.6100e-05],
        [1.6702e-02],
        [1.1468e-02],
        [5.5613e-01],
        [6.9703e-02],
        [1.0000e+00],
        [9.9948e-01],
        [1.0000e+00],
        [4.1130e-03],
        [1.0000e+00],
        [9.9890e-01],
        [1.0000e+00],
        [1.9263e-02],
        [4.9284e-05],
        [1.1729e-03],
        [1.4206e-02],
        [1.0000e+00],
        [5.1304e-05],
        [6.9675e-07],
        [3.1745e-01],
        [9.9986e-01],
        [9.8456e-04],
        [9.8628e-01],
        [2.1284e-04],
        [5.9003e-05],
        [3.3644e-01],
        [9.9998e-01],
        [9.7935e-01],
        [9.4514e-01],
        [1.0000e+00],
        [5.3235e-02],
        [2.0894e-02],
        [4.8201e-04],
        [8.3098e-01],
        [4.8119e-02],
        [6.1536e-01],
        [2.1385e-04],
        [9.9994e-01],
        [1.9128e-04],
        [9.0699e-01],
        [2.5874e-03],
        [2.2579e-01],
        [8.8602e-04],
        [4.4312e-04],
        [3.9892e-06],
        [7.9578e-06],
        [1.4339e-06],
        [9.9999e-01],
        [1.0000e+00],
        [5.4762e-04],
        [3.7200e-04],
        [9.6005e-01],
        [2.9063e-05],
        [9.9997e-01],
        [6.0150e-06],
        [9.7171e-01],
        [1.0000e+00],
        [1.3843e-01],
        [5.5317e-05],
        [9.9999e-01],
        [1.3792e-04],
        [9.9997e-01],
        [4.3699e-01],
        [9.9820e-01],
        [1.0000e+00],
        [4.6385e-01],
        [7.3177e-05],
        [9.9989e-01],
        [2.0722e-02],
        [9.0920e-01],
        [9.0580e-01],
        [8.3851e-01],
        [9.9993e-01],
        [1.5855e-05],
        [9.9679e-01],
        [3.9517e-01],
        [2.5710e-01],
        [1.0000e+00],
        [5.4608e-04],
        [2.9673e-06],
        [7.5940e-01],
        [2.3376e-05],
        [1.0000e+00],
        [1.4867e-04],
        [9.9998e-01],
        [7.0770e-04],
        [1.0000e+00],
        [5.2110e-04],
        [7.5173e-01],
        [1.0000e+00],
        [4.1912e-01],
        [1.9441e-03],
        [1.7946e-04],
        [9.9783e-01],
        [2.8769e-03],
        [7.4124e-05],
        [1.0014e-04],
        [1.2726e-05],
        [6.0100e-02],
        [3.5351e-02],
        [1.9390e-07],
        [4.4035e-01],
        [9.9982e-01],
        [1.3747e-02],
        [8.8280e-01],
        [4.2279e-06],
        [1.0000e+00],
        [3.6821e-02],
        [9.7310e-03],
        [9.9975e-01],
        [1.0000e+00],
        [9.9317e-01],
        [1.8440e-02],
        [9.9925e-01],
        [2.4859e-01],
        [1.0436e-03],
        [9.9999e-01],
        [9.9955e-01],
        [1.2907e-02],
        [1.4431e-04],
        [5.1260e-06],
        [1.0000e+00],
        [2.6505e-03],

In [119]:
model.bias

tensor([-0.1529], dtype=torch.float64, requires_grad=True)